#!/bin/bash

echo "🚀 Démarrage du Blog API avec Interface Web..."
echo ""
echo "✅ Fichiers créés:"
echo "   - public/index.html (Interface Web)"
echo "   - public/style.css (Styles)"
echo "   - public/app.js (Logique JavaScript)"
echo ""
echo "🔌 Configuration:"
echo "   - API Backend: http://localhost:5000/api/articles"
echo "   - Interface Web: http://localhost:5000"
echo "   - Swagger UI: http://localhost:5000/api/docs"
echo ""
echo "📋 Prochaines étapes:"
echo "   1. Assurez-vous que MongoDB Atlas est connecté (.env configuré)"
echo "   2. Exécutez: npm run dev"
echo "   3. Ouvrez votre navigateur sur: http://localhost:5000"
echo ""
echo "✨ C'est tout! L'interface sera prête à utiliser."
echo ""
